### ISSUE TITLE
ChromeAlive Tracker Issue

### ISSUE THREAD

**Issue by blakebyrnes** [ulixee/desktop#2]
## ChromeAlive
- [ ] Can't re-launch Datastore Sessions in ChromeAlive
- [ ] Chromealive devtools panel is closed/blank on first load
- [ ] Chromealive hero-script panel and main page hangs when script comes up. 
   - Tracked down to something after we do Page.navigate first time. Could Electron be waiting for something?
- [ ] Timeline is stopping without showing final state of page 
   - stops at last command.. seems like we actually just want to label the stopping point

### Hero Script
- [x] Hero Script can't see line numbers correctly when inside vm2
- [x] Source code maps don't work when files are relative

### Resources
- [ ] Resources should include mitm work
  - Show original vs mitm (if active)
  - If no mitm, highlight when invalid headers are sent? (use modify headers plugin?)
  - Check all final headers for correctness?
